apiVersion: v1
kind: Service
metadata:
  name: {{ include "aitrism-chart.fullname" . }}-grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: {{ .Values.grafana.nodePort }}
      name: web
  selector:
    app: {{ include "aitrism-chart.fullname" . }}
