global:
  scrape_interval: 15s  # Adjust the scrape interval as needed

scrape_configs:
  # Scrape configuration for the aitrism-service
  - job_name: 'aitrism'
    static_configs:
      - targets: [ 'aitrism:8000' ]

