apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-detect-postgresql-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-csi-sc
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-detect-triggerer-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-csi-sc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-detect-worker-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-csi-sc
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-db-detect-redis-0 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-csi-sc
  resources:
    requests:
      storage: 1Gi
