apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect-rabbitmq
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: detect-rabbitmq
  template:
    metadata:
      labels:
        app: detect-rabbitmq
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}

      volumes:
        - name: config
          emptyDir: {}
        - name: rabbitmq-config-volume
          configMap:
            name: rabbitmq-config
        - name: config-volume
          configMap:
            name: rabbitmq-setup-script
        - name: rabbitmq-advanced-config-volume
          configMap:
            name: rabbitmq-advanced-config
            items:
              - key: advanced.config
                path: advanced.config
        # - name: mongodb-data
        #   persistentVolumeClaim:
        #     claimName: mongodb-pvc

      initContainers:
        - name: rabbitmq-setup
          image: "{{ .Values.rabbitmq.image }}"
          command: ["/bin/sh", "-c"]
          args:
            - "cp /config/setup.sh /tmp/setup.sh && chmod +x /tmp/setup.sh && /tmp/setup.sh"
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: "{{ .Values.rabbitmq.env.erlangCookie }}"

      

      containers:
        - name: rabbitmq
          image: "{{ .Values.rabbitmq.image }}"
          ports:
            - containerPort: {{ .Values.rabbitmq.ports.amqp }}
            - containerPort: {{ .Values.rabbitmq.ports.management }}
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: "{{ .Values.rabbitmq.env.erlangCookie }}"
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.rabbitmq.env.defaultUser }}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.rabbitmq.env.defaultPass }}"
            - name: RABBITMQ_DEFAULT_VHOST
              value: "{{ .Values.rabbitmq.env.defaultVhost }}"
            - name: BROKER_URI
              value: "{{ .Values.rabbitmq.env.BROKER_URI }}"
            - name: BACKEND_URI
              value: "{{ .Values.redis.env.BACKEND_URI }}"
          volumeMounts:
            - name: rabbitmq-advanced-config-volume
              mountPath: /etc/rabbitmq/advanced.config
              subPath: advanced.config

        - name: redis
          image: "{{ .Values.redis.image }}"
          ports:
            - containerPort: {{ .Values.redis.ports.redis }}
          env:
            - name: BACKEND_URI
              value: "{{ .Values.redis.env.BACKEND_URI }}"


      # volumes:
      #   - name: config
      #     emptyDir: {}
      #   - name: rabbitmq-config-volume
      #     configMap:
      #       name: rabbitmq-config
      #   - name: config-volume
      #     configMap:
      #       name: rabbitmq-setup-script
        


