apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
   name: detect
  # labels:
  #       app: aitrism
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: detect-deployment
   # name: {{ include "aitrism-chart.fullname" . }}-celery-worker 
  minReplicas: {{ .Values.celeryWorker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.celeryWorker.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.celeryWorker.autoscaling.targetCPUUtilizationPercentage }}
          #averageUtilization: 40
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.celeryWorker.autoscaling.targetMemoryUtilizationPercentage }}
          #averageUtilization: 40