global:
  scrape_interval: 15s  # Adjust the scrape interval as needed

scrape_configs:
  # Scrape configuration for the aitrism-service
  - job_name: 'aitrism-service'
    static_configs:
      - targets: [ 'a11f9f04b3c944b19a9f4ec469d2a953-1864683ef98c010a.elb.us-east-1.amazonaws.com:8000' ]