apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "detect-master"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-00742829ba98b5748,eipalloc-02a3fa5f3b109e331
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: node-exporter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9100
