apiVersion: v1
kind: Service
metadata:
  name: {{ include "aitrism-chart.fullname" . }}-kafka
spec:
{{/*  type: NodePort*/}}
{{/*  ports:*/}}
{{/*      - port: 9092*/}}
{{/*        nodePort: 31092*/}}
{{/*        name: kafka-port*/}}
  ports:
    - port: {{ .Values.kafka.ports.containerPort }}
      name: kafka-port
    - port: {{ .Values.kafka.ports.internalPort }}
      name: kafka-internal-port
  selector:
    app: {{ include "aitrism-chart.fullname" . }}-kafka
