apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service #{{ include "aitrism-chart.fullname" . }}-zookeeper
spec:
  ports:
    - port: {{ .Values.zookeeper.ports.client }}
      name: client
      targetPort: {{ .Values.zookeeper.ports.client }}
  selector:
    app: {{ include "aitrism-chart.fullname" . }}-zookeeper
