apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9090'
data:
  prometheus.yml: |-
    {{- .Files.Get "files/prometheus.yml" | nindent 4 }}
  rules1.yml: |-
    {{- .Files.Get "files/rules1.yml" | nindent 4 }}
