apiVersion: v1
kind: Service
metadata:
  name: reactapp-service  # You can change the service name as per your preference
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "aitrism-frontend"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0162d9093f3a54888,eipalloc-023c61ed1c5eb854e
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: aitrism  # This should match the label of your React app deployment
  ports:
    - protocol: TCP
      port: 80  # The port the service is exposed on, change as needed
      targetPort: 80  # The target port on the container
  type: LoadBalancer  # Exposes the service externally using a cloud provider's load balancer
