apiVersion: v1
kind: Service
metadata:
  name: {{ include "aitrism-chart.fullname" . }}-kafka
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "aitrism-kafka"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0cfaf32b6224439df,eipalloc-0dfae26afc6dc3f39
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
{{/*  type: NodePort*/}}
{{/*  ports:*/}}
{{/*      - port: 9092*/}}
{{/*        nodePort: 31092*/}}
{{/*        name: kafka-port*/}}
  type: LoadBalancer
  ports:
    - port: {{ .Values.kafka.ports.containerPort }}
      name: kafka-port
    - port: {{ .Values.kafka.ports.internalPort }}
      name: kafka-internal-port
  selector:
    app: {{ include "aitrism-chart.fullname" . }}-kafka
