apiVersion: v1
kind: ConfigMap
metadata:
  name: react-config
data:
  CONFIG_JS: |
    window._env_ = {
      REACT_APP_BACKEND_API_ENDPOINT: "http://{{ .Values.env.AITRISM_MASTER_DNS }}:8000/api/",
      HOST_ENV: "aws",
    }

