apiVersion: v1
kind: Service
metadata:
  name: aitrism
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "aitrism-master"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0cd91c5913823d0bd,eipalloc-06e36fb3ce6fcf9d4
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.ports.prometheus }}
      name: prometheus-port
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: uvicorn-port

    - port: {{ .Values.service.ports.grafana }}
      name: grafana-port
    - port: {{ .Values.service.ports.rabbitmqManagement }}
      name: rabbitmq-management-port
    - port: {{ .Values.service.ports.rabbitmq }}
      name: rabbitmq-port
    - port: 6379
      name: redis
    - port: 9092
      name: kafka
  selector:
    app: aitrism
